name: Report Names Used in Coordinated Spam Threads (with many bots talking to each other)
description: Report account names and aliases (fake names of people) mentioned in coordinated spam threads, with many bots talking to each other and "recommending" a scammer (like an 'expert investor')
title: "Scam Thread Submission"
labels: ["scam-thread"]
body:
  - type: markdown
    attributes:
      value: |      
        Please use this issues template to submit spam threads. Do not do a pull request.
  - type: checkboxes
    id: not-already-in-list
    attributes:
      label: Duplicate Submissions
      description: Check to make sure the names(s) are not already in the list. Go to the latest list of names and do Ctrl+F to search - https://github.com/ThioJoe/YT-Spam-Domains-List/blob/main/SpamThreadsList.txt
      options:
        - label: Yes, I checked that the name **is not currently in the list**
          required: true
        - label: I read the wiki explaining each different categories and examples before submitting
          required: true
  - type: textarea
    id: spam-comment-links
    attributes:
      label: (Required) Spam Comment Direct Link
      description: Direct links to an example of a spam bot referencing the spammer name in a comment.
      placeholder: Enter at least one direct comment link per scammer name you want to submit.
    validations:
      required: true      
  - type: textarea
    id: screenshots
    attributes:
      label: (Optional) Screenshot of comments referencing the scammer names
      description: While not required, please submit a screenshot of the spam comment(s)
      placeholder: (Screenshots can be attached by dragging and dropping image files here)
    validations:
      required: false
  - type: textarea
    id: thread-list
    attributes:
      label: (Required) List of the scammer names
      description: Enter one name per line, and only use lower case letters
      placeholder: Enter one name per line, and only use lower case letters
    validations:
      required: true