---
name: "auto-release"

on:
  push:
    paths:
      - "SpamDomainsList.txt"

jobs:
  auto-release:
    name: "Auto Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: set env
        run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.NOW }}"
          prerelease: false
          title: "${{ env.NOW }}"
          files: |
            SpamDomainsList.txt
